# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому перешел на этот плагин. Он тоже хорош :-)

# Создаем книгу
POST http://localhost:8000/books/ HTTP/1.1
content-type: application/json

{
    "title": "Wrong Code",
    "author": "Robert Martin",
    "pages": 10,
    "year": 2007
}

###

# Получаем список книг
GET http://localhost:8000/books/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/books/0 HTTP/1.1

###

# Обновляем поля в данных о книге
PUT http://localhost:8000/books/0 HTTP/1.1
content-type: application/json

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 10,
    "year": 2007,
    "id": 0
}

###

# Удаляем книгу
DELETE http://localhost:8000/books/0 HTTP/1.1
content-type: application/json

###