# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому перешел на этот плагин. Он тоже хорош :-)

# Создаем книгу
POST http://localhost:8000/api/v1/books/ HTTP/1.1
content-type: application/json

{
    "title": "Wrong Code",
    "author": "Robert Martin",
    "pages": 104,
    "year": 2007,
    "seller_id": 2
}

###

# Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/1 HTTP/1.1

###

# Обновляем поля в данных о книге
PUT http://localhost:8000/api/v1/books/4 HTTP/1.1
content-type: application/json

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 10,
    "year": 2007,
    "seller_id": 3,
    "id": 0
}

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/2 HTTP/1.1
content-type: application/json

###

# Создаем продавца

POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
content-type: application/json

{
    "first_name": "Arnold",
    "last_name": "Shwarzenegger",
    "email": "terminator@mail.ru",
    "password": "123"
}

###

# Получаем продавца по его ID

GET http://localhost:8000/api/v1/sellers/3 HTTP/1.1

###

# Получение списка всех продавцов

GET http://localhost:8000/api/v1/sellers/ HTTP/1.1

###

# Одновление данных продавца 

PUT http://localhost:8000/api/v1/sellers/2 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Sylvester",
    "last_name": "Stallone",
    "email": "rambo@gmail.com"
}

###

# Удаляем продавца
DELETE http://localhost:8000/api/v1/sellers/1 HTTP/1.1
content-type: application/json

###